name: Go4 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-ubuntu:
    name: Build pack on Ubuntu with root docker
    runs-on: ubuntu-latest
    container:
      image: rootproject/root

    strategy:
      fail-fast: false

    steps:
      - name: Install Qt6
        run: |
          rm -f /etc/apt/sources.list.d/archive_uri-*
          apt-get update || true
          apt-get install -y qt6-base-dev

      - name: Checkout pack repository
        uses: actions/checkout@v1

      - name: Configure
        shell: bash
        run: |
          cmake --version
          cmake \
            -S . \
            -B build \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir

      - name: Build
        shell: bash
        run: cmake --build build
